#!/usr/bin/env python
"""Phase 7 - system simulation: drive scripts/app.py through the three required
scenarios and capture the results to results/simulation_log.txt.

Scenarios (from PLAN.md Phase 7):
  1. Unauthorized (image) - an impostor face -> ACCESS DENIED at the face step.
  2. Unauthorized (audio) - member A's face + member B's voice -> ACCESS DENIED at
     the voice step (the identity cross-check rejects a mismatched speaker).
  3. Full valid transaction - member A's face + member A's voice -> ACCESS GRANTED
     and the predicted product is displayed.

Each scenario runs the real CLI as a subprocess (exactly as a user/grader would) and is
checked against its expected exit code. Run:  python scripts/run_simulation.py
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "scripts" / "app.py"
LOG = ROOT / "results" / "simulation_log.txt"

# Backend chatter from MediaPipe / TFLite that we strip so the log stays readable.
NOISE = (
    "WARNING", "W0000", "I0000", "E0000", "INFO:", "feedback", "XNNPACK",
    "clearcut", "Source Location", "wireless/", "_get_loop", "zmq", "delegate",
    "TensorFlow Lite", "ms_per",
)

SCENARIOS = [
    {
        "title": "1. Unauthorized attempt (IMAGE) - impostor face",
        "face": "image_data/impostor/impostor.jpg",
        "voice": "audio_data/Hassan_Adelani_Luqman/confirm_transaction.wav",
        "expect_exit": 1,
        "expect": "ACCESS DENIED at the facial-recognition step",
    },
    {
        "title": "2. Unauthorized attempt (AUDIO) - Hassan's face + Gentil's voice",
        "face": "image_data/Hassan_Adelani_Luqman/neutral.jpg",
        "voice": "audio_data/Gentil_Tonny_Christian_Iradukunda/confirm_transaction.wav",
        "expect_exit": 1,
        "expect": "ACCESS DENIED at the voice step (voice identity != recognised face)",
    },
    {
        "title": "3. Full valid transaction - Hassan's face + Hassan's voice",
        "face": "image_data/Hassan_Adelani_Luqman/neutral.jpg",
        "voice": "audio_data/Hassan_Adelani_Luqman/confirm_transaction.wav",
        "expect_exit": 0,
        "expect": "ACCESS GRANTED, predicted product displayed",
    },
]


def clean(text: str) -> str:
    return "\n".join(line for line in text.splitlines()
                     if line.strip() and not any(n in line for n in NOISE))


def main() -> None:
    out: list[str] = [
        "=" * 72,
        " GROUP 19 - MULTIMODAL SYSTEM SIMULATION LOG (Phase 7)",
        " Generated by: python scripts/run_simulation.py",
        " Each scenario runs the real CLI: python scripts/app.py --face <img> --voice <wav>",
        "=" * 72,
    ]
    all_pass = True
    for s in SCENARIOS:
        cmd = [sys.executable, str(APP), "--face", s["face"], "--voice", s["voice"]]
        proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
        passed = proc.returncode == s["expect_exit"]
        all_pass = all_pass and passed
        out += [
            "",
            "#" * 72,
            f"# SCENARIO {s['title']}",
            f"# expected : {s['expect']}",
            f"# command  : python scripts/app.py --face {s['face']} --voice {s['voice']}",
            "#" * 72,
            clean(proc.stdout + proc.stderr),
            f"[exit {proc.returncode}]  ->  {'PASS' if passed else 'FAIL'} "
            f"(expected exit {s['expect_exit']})",
        ]
    out += [
        "",
        "=" * 72,
        f" RESULT: {'ALL 3 SCENARIOS PASSED' if all_pass else 'SOME SCENARIOS FAILED'}",
        "=" * 72,
    ]
    report = "\n".join(out) + "\n"
    LOG.parent.mkdir(parents=True, exist_ok=True)
    LOG.write_text(report, encoding="utf-8")
    print(report)
    print(f"Wrote {LOG.relative_to(ROOT)}")
    sys.exit(0 if all_pass else 1)


if __name__ == "__main__":
    main()
